from enum import Enum

class Building(Enum):
    FACTORY_RAW_MATERIALS = 'FACTORY_RAW_MATERIALS'
    REGIONAL_RAW_MATERIALS = 'REGIONAL_RAW_MATERIALS'
    BUILDING_SUPPLIES_STORE = 'BUILDING_SUPPLIES_STORE'
    FARMER_S_MARKET = 'FARMER_S_MARKET'
    GARDENING_SUPPLIES = 'GARDENING_SUPPLIES'
    HARDWARE_STORE = 'HARDWARE_STORE'
    FASHION_STORE = 'FASHION_STORE'
    HOME_APPLIANCES = 'HOME_APPLIANCES'
    FURNITURE_STORE = 'FURNITURE_STORE'
    DONUT_SHOP = 'DONUT_SHOP'
    FAST_FOOD_RESTAURANT = 'FAST_FOOD_RESTAURANT'
    SPORT_SHOP = 'SPORT_SHOP'
    TOY_SHOP = 'TOY_SHOP'
    COUNTRY_STORE = 'COUNTRY_STORE'
    BUREAU_OF_RESTORATION = 'BUREAU_OF_RESTORATION'
    DESERT_SHOP = 'DESERT_SHOP'
    ECO_SHOP = 'ECO_SHOP'
    CAR_PARTS = 'CAR_PARTS'
    FISH_MARKETPLACE = 'FISH_MARKETPLACE'
    SILK_STORE = 'SILK_STORE'
    TROPICAL_PRODUCTS_STORE = 'TROPICAL_PRODUCTS_STORE'
    PARISIAN_ITEMS = 'PARISIAN_ITEMS'
    SANTA_S_WORKSHOP = 'SANTA_S_WORKSHOP'
    CHOCOLATE_FACTORY = 'CHOCOLATE_FACTORY'
    TRAIN_ITEMS = 'TRAIN_ITEMS'
    VU_RANDOM_GENERATOR = 'VU_RANDOM_GENERATOR'

def get_commercial_building():
   return [
        Building.TOY_SHOP,
        Building.BUILDING_SUPPLIES_STORE,
        Building.GARDENING_SUPPLIES,
        Building.FARMER_S_MARKET,
        Building.HARDWARE_STORE,
        Building.FASHION_STORE,
        Building.HOME_APPLIANCES,
        Building.FURNITURE_STORE,
        Building.DONUT_SHOP,
        Building.FAST_FOOD_RESTAURANT,
        Building.DESERT_SHOP,
        Building.COUNTRY_STORE,
        Building.SPORT_SHOP,
        Building.BUREAU_OF_RESTORATION,
        Building.VU_RANDOM_GENERATOR
    ]
