from enum import Enum

class Miscellaneous(Enum):
    TRADE_BOX='misc/trade_box.png'
    PURCHASE_COMPLETED='misc/purchase_completed.png'
    REFRESH='misc/refresh_2.png'
    FRIENDS = 'misc/friends.png'
    CONTRUCTION_HAT = 'misc/contruction_hat.png'
    CONFIRM_ICON = 'misc/confirm_icon.png'
    RECYCLED_FABRIC = 'misc/recycled_fabric.png'
    RECYCLED_FABRIC_2 = 'misc/recycled_fabric_2.png'
    COIN = 'misc/coin.png'
    REGIONS = 'misc/regions.png'
    EMPTY_BOX = 'misc/empty_box.png'
    DANIEL_FACE = 'misc/daniel_face.png'
    PLUS_ICON = 'misc/plus_icon.png'
    DANIEL_TRADE_ICON = 'misc/daniel_trade_icon.png'
    GLOBAL_TRADE_HQ_COIN = 'misc/global_trade_hq_coin.png'
    TRADE_DEPOT_COIN = 'misc/trade_depot_coin.png'
    OK = 'misc/ok.png'
    TEST = 'misc/img.png'
    ALREADY_REFRESHED = 'misc/already_refreshed.png'
    REMOTE_TRADE_DEPOT_ICON = 'misc/remote_trade_depot.png'
    IMG = 'misc/img_1.png'
    BACKPACK = 'misc/backpack.png'

    # ITEM_BOXES='misc/item_boxes.png'
    ITEM_BOXES='misc/item_boxes.png'
    EMPTY_TRADE_BOXES='misc/empty_trade_boxes.png'
    ADVERTISE_ICON='misc/advertise_icon.png'
    COMMERCIAL_INFO_ICON='misc/commercial_info_icon.png'
    GO_TO_REGIONS_BUTTON='misc/go_to_regions_button.png'
    CARGO_SHIP_ICON='misc/cargo_ship_icon.png'
    HOME_TRADE_ICON='misc/home_trade_icon.png'

    STORAGE='misc/storage.png'
    GLOBAL_TRADE_HQ='misc/global_trade_hq.png'
    CLOSE='misc/close.png'
    CREATE_SALE='misc/create_sale.png'
    MY_TRADE_DEPOT='misc/my_trade_depot.png'
    VISITNG_TRADE_DEPOT='misc/visiting_trade_depot.png'
    HOME='misc/home.png'
    TRADE_DEPOT_NAME='misc/trade_depot_name.png'
    MISSING_ITEMS='misc/missing_items.png'
    EMPTY='misc/empty.png'
    EMPTY2='misc/empty2.png'
    CITY_STORAGE_PURCHASE_COMPLETED='misc/purchase_completed.png'

    SUNSHINE_VALLEY='misc/sunshine_valley.png'
    BARLEYCORN_POINTS='misc/barleycorn_point.png'
    TRADER_RIDGE='misc/trader_ridge.png'
    MAGNOLIA_WETLANDS='misc/magnolia_wetlands.png'
    NAUTILUS_PLATEAU='misc/nautilus_plateau.png'
    HOKUSAI_CLIFFS='misc/hokusai_cliffs.png'
    COTTONWOOD_FOREST='misc/cottonwood_forest.png'
    GRAND_HAVEN='misc/grand_haven.png'
    JUGBAND_HILLS='misc/jugband_hills.png'
